version: '3'
services:
  frontend:
    build: .
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
